name: PR Helper - main

concurrency: 
    group: ${{ github.head_ref }}
    cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  pull_request_review:
    branches:
      - main
  issue_comment:
    branches:
      - main

jobs:
  prhelper_job_main:
    runs-on: ubuntu-latest
    steps:
    - name: Run PR Helper on Schedule
      id: runprhelper_main
      uses: Matticusau/pr-helper@v1.2.6
      with:
        repo-token: ${{ secrets.ADMIN_PAT }}
        enable-prmerge-automation: true
        enable-prcomment-automation: true
        enable-prlabel-automation: true
        enable-prreviewer-frontmatter: true
        enable-welcomemessage: true
        welcome-message: "Thanks for opening an issue! When you are ready for the pr to be reviewed / merged add the pr-ready label."
        prmerge-requireallchecks: true
        prmerge-requirereviewcount: 1
        prmerge-method: 'merge'
        prmerge-deletebranch: 'true'
        prmerge-deletebranch-config: '{"deny":["develop", "main", "gh-pages"]}'
        prlabel-default: 'pr-ready'
        prlabel-ready: 'pr-ready'
        prlabel-onhold: 'pr-onhold'
        prlabel-reviewrequired: 'review-required'
        prlabel-automerge: 'auto-merge'
